### ISSUE TITLE
Athenian Champion's Ram Head

### ISSUE THREAD

**Issue by Wololoooo** [n4bb12/celeste-search#25]
Please can we show max / min stats for Athenian Champion's Ram Head.
Yes lvl 35 can be a store item of fixed stats but it does also drop with varying stats.
Thanks

**Comment by n4bb12** [comment]
thanks for reporting

**Comment by n4bb12** [comment]
according to pf2k it's the only item that is sold and can drop
currently the logic is that for sold items the range is not shown
i'll have to add an exception for this one

**Comment by n4bb12** [comment]
https://celeste-search.netlify.com/?tab=0&search=Athenian__Champion%27s__Ram__Head

**Comment by Wololoooo** [comment]
Thanks for getting back to me and oh so quick :)
PF2K is a bit adrift - there are several items that are in shops (at
default stats) & can also drop with varying stats

example - Please look at item Athena's Golden Gorget.in Light Armor section:
This item drops at levels 35 to 39 and is also available at a game shop at
lvl 35 with default stats.

regards,
Steve.

**Comment by Wololoooo** [comment]
hi again
I just checked - all 7 items in Athens Basic Store can drop at several
levels with variable stats & can be bought in the store at lvl 35 with
default stats

regards,
Steve

**Comment by n4bb12** [comment]
![celeste-search netlify com__tab=0 search=Athenian__Champion%27s__Ram__Head](https://user-images.githubusercontent.com/6810177/67593821-4e5c3700-f763-11e9-9efe-ddb9e00bd5a5.png)

**Comment by Wololoooo** [comment]
Looks great - many thanks
