### ISSUE TITLE
Visual bug: blueprint material

### ISSUE THREAD

**Issue by System-Glitch** [n4bb12/celeste-search#6]
The materials needed for blueprints are not correctly displayed as shown in the following screenshot: 
![before](https://user-images.githubusercontent.com/7251668/56747663-ad260100-677e-11e9-9f9e-1f5fd0f75aeb.png)

Tested on firefox and chrome.

**Simple fix:** adding an additional span after the material name aligns everything correctly. (The same technique is already used for craftable items materials)
![fixed](https://user-images.githubusercontent.com/7251668/56747733-cc249300-677e-11e9-949c-958d2de5b74c.png)

Example:
```html
<span _ngcontent-ugl-c11="" class="icon--materials icon--materials--36"></span>
<span _ngcontent-ugl-c11="" class="__mat-amount">30</span>
<span _ngcontent-ugl-c11="" class="__mat-text --epic">Obsidian Blocks</span>
<span></span> <!-- Add this -->
```

**Comment by n4bb12** [comment]
https://search.projectceleste.com/?tab=2&search=edges
