### ISSUE TITLE
city names missing from shop names

### ISSUE THREAD

**Issue by lukipr0** [n4bb12/celeste-search#8]
items.projectceleste.com gives this result:

Crete Cohort Heavy Spear
Purchasable at **Crete,** Magnificent Minoan Gear Store

whereas search.projectceleste.com gives this result:

Crete Cohort Heavy Spear
Purchasable at Magnificent Minoan Gear Store

since there is no city of Minos, a new player won't know where to go to buy this item. so the city name should be in there like on the old page.

PS: of course this goes for all purchaseable items. they all need the city's name mentioned, where you can buy it. just exactly like the old page did. thank youuu:))

**Comment by n4bb12** [comment]
Unfortunately it's not an accident.

I've collected the location data for the old search manually. For the new search I've switched to data from the official API which does not include the location.

We could add that information back in by augmenting each store with its location.

**Comment by n4bb12** [comment]
![2019-04-27 Screenshot 001](https://user-images.githubusercontent.com/6810177/56849954-e20b9280-68fb-11e9-999f-3c9fefd9ae24.png)

**Comment by n4bb12** [comment]
Thanks for helping me with this one 🤺
